# Generated by Django 5.0.6 on 2024-07-03 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xboxuser',
            name='clearance_id',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='xboxuser',
            name='spartan_token',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='xboxuser',
            name='tokens_refreshed_at',
            field=models.DateTimeField(null=True),
        ),
    ]
