# Generated by Django 5.0.6 on 2024-07-04 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0002_xboxuser_clearance_id_xboxuser_spartan_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRecord',
            fields=[
                ('time_played', models.DurationField()),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('xbox_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='haloinfinite.xboxuser')),
            ],
        ),
    ]
