# Generated by Django 5.0.6 on 2024-07-04 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0004_xboxuser_refresh_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xboxuser',
            name='xuid',
            field=models.CharField(),
        ),
    ]
