# Generated by Django 5.0.6 on 2024-07-04 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0005_alter_xboxuser_xuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerecord',
            name='matches_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='ties',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
