# Generated by Django 5.0.6 on 2024-07-04 20:47

import annoying.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0006_servicerecord_matches_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerecord',
            name='time_played',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='servicerecord',
            name='xbox_user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='haloinfinite.xboxuser'),
        ),
    ]
