# Generated by Django 5.0.6 on 2024-07-04 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0007_alter_servicerecord_time_played_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField()),
                ('version_id', models.UUIDField()),
                ('public_name', models.CharField(null=True)),
                ('description', models.CharField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField()),
                ('outcome', models.CharField()),
                ('rank', models.IntegerField(null=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('lifecycle_mode', models.CharField()),
                ('game_variant', models.CharField()),
                ('level_external_id', models.UUIDField()),
                ('season_external_id', models.CharField(null=True)),
                ('rounds_won', models.IntegerField(default=0)),
                ('rounds_lost', models.IntegerField(default=0)),
                ('rounds_tied', models.IntegerField(default=0)),
                ('kills', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('callout_assists', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('max_killing_spree', models.IntegerField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('pre_match_csr', models.IntegerField(default=0)),
                ('post_match_csr', models.IntegerField(default=0)),
                ('xbox_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haloinfinite.xboxuser')),
                ('playlist_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haloinfinite.playlistasset')),
            ],
        ),
    ]
