# Generated by Django 5.0.6 on 2024-07-04 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0008_playlistasset_match'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlistasset',
            old_name='version_id',
            new_name='version_external_id',
        ),
    ]
