# Generated by Django 5.0.6 on 2024-07-04 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0009_rename_version_id_playlistasset_version_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='playlist_asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haloinfinite.playlistasset'),
        ),
    ]
