# Generated by Django 5.0.6 on 2024-07-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0010_alter_match_playlist_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='id',
        ),
        migrations.AlterField(
            model_name='match',
            name='external_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
