# Generated by Django 5.0.6 on 2024-07-04 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0011_remove_match_id_alter_match_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stats_retrieved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playlistasset',
            name='info_retrieved',
            field=models.BooleanField(default=False),
        ),
    ]
