# Generated by Django 5.0.6 on 2024-07-09 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haloinfinite', '0012_match_stats_retrieved_playlistasset_info_retrieved'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPlaylistCSR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('tier', models.CharField(default=None, null=True)),
                ('tier_start', models.IntegerField(default=0)),
                ('sub_tier', models.CharField(default=None, null=True)),
                ('next_tier', models.CharField(default=None, null=True)),
                ('next_tier_start', models.IntegerField(default=0)),
                ('next_sub_tier', models.CharField(default=None, null=True)),
                ('playlist_asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='haloinfinite.playlistasset')),
                ('xbox_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haloinfinite.xboxuser')),
            ],
        ),
    ]
